@startuml GrowManager_C4Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml
!include FONTAWESOME/server.puml
!include DEVICONS/database.puml
!include FONTAWESOME/server.puml
!include DEVICONS/bootstrap.puml
!include DEVICONS/wordpress.puml

LAYOUT_WITH_LEGEND()

title GrowManager C4Container-Diagramm

SHOW_PERSON_OUTLINE()
Person(user, User, "Angemeldeter Benutzer")

System_Boundary(growmanager, "GrowManager ") {
    Container(backend, "Backend", "SpringBoot Application", "Business-Logik, Datenbankverbindung, Web-Controller, Exceptions, Domain-Klassen")
    Container(frontend, "Thymeleaf-Frontend", "Java-Template-Engine", "Auf Basis von HTML-Code wird das Frontend erstellt - Kommunikation mit Backend über Thymeleaf")
    }

Container(webserver, "Apache Web Server", "HTTP Server", "Hostet den GrowManager", "server")
ContainerDb(database, "Datenbank", "MySQL", "Speichert die Inhalte der Website sowie die Informationen der User", "database")

System_Ext(host, "XAMPP", "Stellt im Probebetrieb Serverressourcen und Datenbank bereit")

Rel(frontend, webserver, "HTTP", "Liefert Web-Seiten an Benutzer aus")
Rel(webserver, backend, "HTTP", "Verarbeitet Anfragen und antwortet mit Daten")
Rel(backend, database, "JPA", "Speichert und liest Daten aus/auf Datenbank")

Rel(webserver, host, "Gehostet von")
Rel(database, host, "Gehostet von")

Rel(user, growmanager, "HTTP", "verwendet")


@enduml