@startuml USE-CaseKrankenhaus
skinparam actorStyle awesome

skinparam usecase {
BackgroundColor DarkSeaGreen
BorderColor DarkSlateGray

BackgroundColor<< Main >> YellowGreen
BorderColor<< Main >> YellowGreen

ArrowColor Olive
ActorBorderColor black
ActorFontName Courier

ActorBackgroundColor<< Human >> Gold
}
left to right direction
actor :Verwaltung1: as V
actor :Verwaltung2: as V2
actor :Adressdatenbank: as ADB

rectangle Anwendungssystem {
    
  V -- (Mitarbeiter einstellen)
  V -- (Mitarbeiter entlassen)
  V -- (Patient aufnehmen)
  V -- (Patient entlassen)
  V2 -- (Patient aufnehmen)
  V2 -- (Patient entlassen)
  (Mitarbeiter einstellen) .> (Daten erfassen) : include
  (Patient aufnehmen) .> (Daten erfassen) : include
  (Daten erfassen) <. (Adressvalidierung) : extends
  (Adressvalidierung) -- ADB
}
@enduml
